package api

import (
	"time"

	"github.com/mbreese/batchq/jobs"
)

// ErrorResponse is the JSON body returned for any non-2xx response.
type ErrorResponse struct {
	Error   string `json:"error"`
	Code    string `json:"code,omitempty"`
	Details string `json:"details,omitempty"`
}

// JobDTO is the wire representation of a batchq job.
//
// Differences from jobs.JobDef:
//   - Status is a string (the StatusCode name) for readability.
//   - Details and RunningDetails are maps for easier JSON consumption.
//   - Zero-valued times are omitted instead of serializing as "0001-01-01...".
type JobDTO struct {
	JobID          string            `json:"job_id"`
	Status         string            `json:"status"`
	Priority       int               `json:"priority"`
	Name           string            `json:"name"`
	Notes          string            `json:"notes,omitempty"`
	SubmitTime     *time.Time        `json:"submit_time,omitempty"`
	StartTime      *time.Time        `json:"start_time,omitempty"`
	EndTime        *time.Time        `json:"end_time,omitempty"`
	ReturnCode     int               `json:"return_code"`
	AfterOk        []string          `json:"after_ok,omitempty"`
	Details        map[string]string `json:"details,omitempty"`
	RunningDetails map[string]string `json:"running_details,omitempty"`

	// Optional submit-time metadata. Empty values are omitted from JSON.
	InputFiles  []string `json:"input_files,omitempty"`
	OutputFiles []string `json:"output_files,omitempty"`
}

// JobFromDef converts a storage/jobs JobDef into a wire DTO.
func JobFromDef(j *jobs.JobDef) *JobDTO {
	if j == nil {
		return nil
	}
	dto := &JobDTO{
		JobID:      j.JobId,
		Status:     j.Status.String(),
		Priority:   j.Priority,
		Name:       j.Name,
		Notes:      j.Notes,
		ReturnCode: j.ReturnCode,
		AfterOk:    j.AfterOk,
	}
	if !j.SubmitTime.IsZero() {
		t := j.SubmitTime.UTC()
		dto.SubmitTime = &t
	}
	if !j.StartTime.IsZero() {
		t := j.StartTime.UTC()
		dto.StartTime = &t
	}
	if !j.EndTime.IsZero() {
		t := j.EndTime.UTC()
		dto.EndTime = &t
	}
	if len(j.Details) > 0 {
		dto.Details = make(map[string]string, len(j.Details))
		for _, d := range j.Details {
			dto.Details[d.Key] = d.Value
		}
	}
	if len(j.RunningDetails) > 0 {
		dto.RunningDetails = make(map[string]string, len(j.RunningDetails))
		for _, d := range j.RunningDetails {
			dto.RunningDetails[d.Key] = d.Value
		}
	}
	if len(j.InputFiles) > 0 {
		dto.InputFiles = append([]string(nil), j.InputFiles...)
	}
	if len(j.OutputFiles) > 0 {
		dto.OutputFiles = append([]string(nil), j.OutputFiles...)
	}
	return dto
}

// JobToDef converts a wire DTO into a JobDef. Used by the server to accept
// incoming SubmitJobRequest payloads; the Status field is ignored (the
// server decides it from the dependency list).
func JobToDef(dto *JobDTO) *jobs.JobDef {
	if dto == nil {
		return nil
	}
	j := &jobs.JobDef{
		JobId:      dto.JobID,
		Priority:   dto.Priority,
		Name:       dto.Name,
		Notes:      dto.Notes,
		ReturnCode: dto.ReturnCode,
		AfterOk:    dto.AfterOk,
	}
	if dto.SubmitTime != nil {
		j.SubmitTime = *dto.SubmitTime
	}
	if dto.StartTime != nil {
		j.StartTime = *dto.StartTime
	}
	if dto.EndTime != nil {
		j.EndTime = *dto.EndTime
	}
	for k, v := range dto.Details {
		j.Details = append(j.Details, jobs.JobDefDetail{Key: k, Value: v})
	}
	for k, v := range dto.RunningDetails {
		j.RunningDetails = append(j.RunningDetails, jobs.JobRunningDetail{Key: k, Value: v})
	}
	if len(dto.InputFiles) > 0 {
		j.InputFiles = append([]string(nil), dto.InputFiles...)
	}
	if len(dto.OutputFiles) > 0 {
		j.OutputFiles = append([]string(nil), dto.OutputFiles...)
	}
	return j
}

// --- Requests / responses ---------------------------------------------

// HealthResponse is the body of GET /healthz. InstanceID is a UUID
// generated by the server at startup; the server's own ownership
// monitor uses it to detect when the socket path has been replaced
// by a different server.
type HealthResponse struct {
	Status     string `json:"status"`
	InstanceID string `json:"instance_id"`
}

// SubmitJobRequest is the body for POST /jobs. Status is ignored on the
// wire; if Hold=true the server starts the job in USERHOLD instead of
// computing the status from deps.
type SubmitJobRequest struct {
	Name        string            `json:"name,omitempty"`
	Notes       string            `json:"notes,omitempty"`
	Priority    int               `json:"priority,omitempty"`
	Hold        bool              `json:"hold,omitempty"`
	AfterOk     []string          `json:"after_ok,omitempty"`
	Details     map[string]string `json:"details,omitempty"`
	InputFiles  []string          `json:"input_files,omitempty"`
	OutputFiles []string          `json:"output_files,omitempty"`
}

// SubmitJobResponse returns the canonical job ID and the persisted job.
type SubmitJobResponse struct {
	Job *JobDTO `json:"job"`
}

// ListJobsResponse is the body of GET /jobs and friends.
type ListJobsResponse struct {
	Jobs []*JobDTO `json:"jobs"`
}

// JobResponse wraps a single job (for GET /jobs/{id}).
type JobResponse struct {
	Job *JobDTO `json:"job"`
}

// JobDependentsResponse is the body of GET /jobs/{id}/dependents.
type JobDependentsResponse struct {
	JobIDs []string `json:"job_ids"`
}

// StatusCountsResponse is the body of GET /queue/counts.
type StatusCountsResponse struct {
	Counts map[string]int `json:"counts"`
}

// PriorityRequest is the body of POST /jobs/{id}/priority.
type PriorityRequest struct {
	Delta int `json:"delta"`
}

// CancelJobRequest is the body of DELETE /jobs/{id} (when a reason is
// provided). DELETE typically has no body, but clients can include one to
// pass a custom reason.
type CancelJobRequest struct {
	Reason string `json:"reason,omitempty"`
}

// ClaimJobRequest is the body of POST /runners/{runner_id}/claim. The
// server uses this to filter candidate jobs by resource limits.
type ClaimJobRequest struct {
	Kind           string `json:"kind"` // "simple" or "slurm"
	MaxProcs       int    `json:"max_procs,omitempty"`
	MaxMemoryMB    int    `json:"max_memory_mb,omitempty"`
	MaxWalltimeSec int    `json:"max_walltime_sec,omitempty"`
}

// ClaimJobResponse is the body of a successful claim. If Job is nil, no
// job was claimed; MoreEligible indicates whether QUEUED jobs remain that
// did not fit the limits.
type ClaimJobResponse struct {
	Job          *JobDTO `json:"job,omitempty"`
	MoreEligible bool    `json:"more_eligible"`
}

// ProxyJobRequest is the body of POST /runners/{runner_id}/jobs/{id}/proxy.
type ProxyJobRequest struct {
	RunningDetails map[string]string `json:"running_details,omitempty"`
}

// RunningDetailsRequest is the body of PATCH /runners/{runner_id}/jobs/{id}/running.
type RunningDetailsRequest struct {
	Details map[string]string `json:"details"`
}

// EndJobRequest is the body of POST /runners/{runner_id}/jobs/{id}/end.
type EndJobRequest struct {
	ReturnCode int `json:"return_code"`
}

// EndProxyRequest is the body of POST /runners/{runner_id}/jobs/{id}/proxy-end.
type EndProxyRequest struct {
	Status     string     `json:"status"`     // "SUCCESS", "FAILED", "CANCELED"
	StartTime  *time.Time `json:"start_time,omitempty"`
	EndTime    *time.Time `json:"end_time,omitempty"`
	ReturnCode int        `json:"return_code"`
}
